[package]
name = "assuan_rs"
version = "0.0.1"
edition = "2021"
authors = ["Robin Knaapen"]

[dependencies]
derive_more = "0.99.18"
async-std = {version = "1.12.0"}
num_enum = "0.7.2"
strum = { version = "0.26", features = ["derive"] }
