use derive_more::Display;
use std::{fmt, num::ParseIntError};

#[derive(Debug, PartialEq, Clone, Copy)]
#[repr(u16)]
pub enum GpgErrorCode {
    NoError,
    General,
    UnknownPacket,
    UnknownVersion,
    PubkeyAlgo,
    DigestAlgo,
    BadPubkey,
    BadSeckey,
    BadSignature,
    NoPubkey,
    Checksum,
    BadPassphrase,
    CipherAlgo,
    KeyringOpen,
    InvPacket,
    InvArmor,
    NoUserId,
    NoSeckey,
    WrongSeckey,
    BadKey,
    ComprAlgo,
    NoPrime,
    NoEncodingMethod,
    NoEncryptionScheme,
    NoSignatureScheme,
    InvAttr,
    NoValue,
    NotFound,
    ValueNotFound,
    Syntax,
    BadMpi,
    InvPassphrase,
    SigClass,
    ResourceLimit,
    InvKeyring,
    Trustdb,
    BadCert,
    InvUserId,
    Unexpected,
    TimeConflict,
    Keyserver,
    WrongPubkeyAlgo,
    TributeToDA,
    WeakKey,
    InvKeylen,
    InvArg,
    BadUri,
    InvUri,
    Network,
    UnknownHost,
    SelftestFailed,
    NotEncrypted,
    NotProcessed,
    UnusablePubkey,
    UnusableSeckey,
    InvValue,
    BadCertChain,
    MissingCert,
    NoData,
    Bug,
    NotSupported,
    InvOp,
    Timeout,
    Internal,
    EofGcrypt,
    InvObj,
    TooShort,
    TooLarge,
    NoObj,
    NotImplemented,
    Conflict,
    InvCipherMode,
    InvFlag,
    InvHandle,
    Truncated,
    IncompleteLine,
    InvResponse,
    NoAgent,
    Agent,
    InvData,
    AssuanServerFault,
    Assuan,
    InvSessionKey,
    InvSexp,
    UnsupportedAlgorithm,
    NoPinEntry,
    PinEntry,
    BadPin,
    InvName,
    BadData,
    InvParameter,
    WrongCard,
    NoDirmngr,
    Dirmngr,
    CertRevoked,
    NoCrlKnown,
    CrlTooOld,
    LineTooLong,
    NotTrusted,
    Canceled,
    BadCaCert,
    CertExpired,
    CertTooYoung,
    UnsupportedCert,
    UnknownSexp,
    UnsupportedProtection,
    CorruptedProtection,
    AmbiguousName,
    Card,
    CardReset,
    CardRemoved,
    InvCard,
    CardNotPresent,
    NoPkcs15App,
    NotConfirmed,
    Configuration,
    NoPolicyMatch,
    InvIndex,
    InvId,
    NoScdaemon,
    Scdaemon,
    UnsupportedProtocol,
    BadPinMethod,
    CardNotInitialized,
    UnsupportedOperation,
    WrongKeyUsage,
    NothingFound,
    WrongBlobType,
    MissingValue,
    Hardware,
    PinBlocked,
    UseConditions,
    PinNotSynced,
    InvCrl,
    BadBer,
    InvBer,
    ElementNotFound,
    IdentifierNotFound,
    InvTag,
    InvLength,
    InvKeyinfo,
    UnexpectedTag,
    NotDerEncoded,
    NoCmsObj,
    InvCmsObj,
    UnknownCmsObj,
    UnsupportedCmsObj,
    UnsupportedEncoding,
    UnsupportedCmsVersion,
    UnknownAlgorithm,
    InvEngine,
    PubkeyNotTrusted,
    DecryptFailed,
    KeyExpired,
    SigExpired,
    EncodingProblem,
    InvState,
    DupValue,
    MissingAction,
    ModuleNotFound,
    InvOidString,
    InvTime,
    InvCrlObj,
    UnsupportedCrlVersion,
    InvCertObj,
    UnknownName,
    LocaleProblem,
    NotLocked,
    ProtocolViolation,
    InvMac,
    InvRequest,
    UnknownExtn,
    UnknownCritExtn,
    Locked,
    UnknownOption,
    UnknownCommand,
    NotOperational,
    NoPassphrase,
    NoPin,
    NotEnabled,
    NoEngine,
    MissingKey,
    TooMany,
    LimitReached,
    NotInitialized,
    MissingIssuerCert,
    NoKeyserver,
    InvCurve,
    UnknownCurve,
    DupKey,
    Ambiguous,
    NoCryptCtx,
    WrongCryptCtx,
    BadCryptCtx,
    CryptCtxConflict,
    BrokenPubkey,
    BrokenSeckey,
    MacAlgo,
    FullyCanceled,
    Unfinished,

    BufferTooShort,
    SexpInvLenSpec,
    SexpStringTooLong,
    SexpUnmatchedParen,
    SexpNotCanonical,
    SexpBadCharacter,
    SexpBadQuotation,
    SexpZeroPrefix,
    SexpNestedDh,
    SexpUnmatchedDh,
    SexpUnexpectedPunc,
    SexpBadHexChar,
    SexpOddHexNumbers,
    SexpBadOctChar,
    SubkeysExpOrRev,
    DbCorrupted,
    ServerFailed,
    NoName,
    NoKey,
    LegacyKey,
    RequestTooShort,
    RequestTooLong,
    ObjTermState,
    NoCertChain,
    CertTooLarge,
    InvRecord,
    BadMac,
    UnexpectedMsg,
    ComprFailed,
    WouldWrap,
    FatalAlert,
    NoCipher,
    MissingClientCert,
    CloseNotify,
    TicketExpired,
    BadTicket,
    UnknownIdentity,
    BadHsCert,
    BadHsCertReq,
    BadHsCertVer,
    BadHsChangeCipher,
    BadHsClientHello,
    BadHsServerHello,
    BadHsServerHelloDone,
    BadHsFinished,
    BadHsServerKex,
    BadHsClientKex,
    BogusString,
    Forbidden,
    KeyDisabled,
    KeyOnCard,
    InvLockObj,
    True,
    False,
    AssGeneral,
    AssAcceptFailed,
    AssConnectFailed,
    AssInvResponse,
    AssInvValue,
    AssIncompleteLine,
    AssLineTooLong,
    AssNestedCommands,
    AssNoDataCb,
    AssNoInquireCb,
    AssNotAServer,
    AssNotAClient,
    AssServerStart,
    AssReadError,
    AssWriteError,
    AssTooMuchData,
    AssUnexpectedCmd,
    AssUnknownCmd,
    AssSyntax,
    AssCanceled,
    AssNoInput,
    AssNoOutput,
    AssParameter,
    AssUnknownInquire,

    EngineTooOld,
    WindowTooSmall,
    WindowTooLarge,
    MissingEnvvar,
    UserIdExists,
    NameExists,
    DupName,
    TooYoung,
    TooOld,
    UnknownFlag,
    InvOrder,
    AlreadyFetched,
    TryLater,
    WrongName,
    NoAuth,
    BadAuth,
    NoKeyboxd,
    Keyboxd,
    NoService,
    Service,
    BadPuk,
    NoResetCode,
    BadResetCode,

    SystemBug,
    DnsUnknown,
    DnsSection,
    DnsAddress,
    DnsNoQuery,
    DnsNoAnswer,
    DnsClosed,
    DnsVerify,
    DnsTimeout,
    LdapGeneral,
    LdapAttrGeneral,
    LdapNameGeneral,
    LdapSecurityGeneral,
    LdapServiceGeneral,
    LdapUpdateGeneral,
    LdapEGeneral,
    LdapXGeneral,
    LdapOtherGeneral,
    LdapXConnecting,
    LdapReferralLimit,
    LdapClientLoop,
    LdapNoResults,
    LdapControlNotFound,
    LdapNotSupported,
    LdapConnect,
    LdapNoMemory,
    LdapParam,
    LdapUserCancelled,
    LdapFilter,
    LdapAuthUnknown,
    LdapTimeout,
    LdapDecoding,
    LdapEncoding,
    LdapLocal,
    LdapServerDown,
    LdapSuccess,
    LdapOperations,
    LdapProtocol,
    LdapTimelimit,
    LdapSizelimit,
    LdapCompareFalse,
    LdapCompareTrue,
    LdapUnsupportedAuth,
    LdapStrongAuthRqrd,
    LdapPartialResults,
    LdapReferral,
    LdapAdminlimit,
    LdapUnavailCritExtn,
    LdapConfidentRqrd,
    LdapSaslBindInprog,
    LdapNoSuchAttribute,
    LdapUndefinedType,
    LdapBadMatching,
    LdapConstViolation,
    LdapTypeValueExists,
    LdapInvSyntax,
    LdapNoSuchObj,
    LdapAliasProblem,
    LdapInvDnSyntax,
    LdapIsLeaf,
    LdapAliasDeref,
    LdapXProxyAuthFail,
    LdapBadAuth,
    LdapInvCredentials,
    LdapInsufficientAcc,
    LdapBusy,
    LdapUnavailable,
    LdapUnwillToPerform,
    LdapLoopDetect,
    LdapNamingViolation,
    LdapObjClsViolation,
    LdapNotAllowNonleaf,
    LdapNotAllowOnRdn,
    LdapAlreadyExists,
    LdapNoObjClassMods,
    LdapResultsTooLarge,
    LdapAffectsMultDsas,
    LdapVlv,
    LdapOther,
    LdapCupResourceLimit,
    LdapCupSecViolation,
    LdapCupInvData,
    LdapCupUnsupScheme,
    LdapCupReload,
    LdapCancelled,
    LdapNoSuchOperation,
    LdapTooLate,
    LdapCannotCancel,
    LdapAssertionFailed,
    LdapProxAuthDenied,
    User1,
    User2,
    User3,
    User4,
    User5,
    User6,
    User7,
    User8,
    User9,
    User10,
    User11,
    User12,
    User13,
    User14,
    User15,
    User16,
    SqlOk,
    SqlError,
    SqlInternal,
    SqlPerm,
    SqlAbort,
    SqlBusy,
    SqlLocked,
    SqlNomem,
    SqlReadonly,
    SqlInterrupt,
    SqlIoerr,
    SqlCorrupt,
    SqlNotfound,
    SqlFull,
    SqlCantopen,
    SqlProtocol,
    SqlEmpty,
    SqlSchema,
    SqlToobig,
    SqlConstraint,
    SqlMismatch,
    SqlMisuse,
    SqlNolfs,
    SqlAuth,
    SqlFormat,
    SqlRange,
    SqlNotadb,
    SqlNotice,
    SqlWarning,
    SqlRow,
    SqlDone,
    MissingErrno,
    UnknownErrno,
    Eof,

    E2big,
    Eacces,
    Eaddrinuse,
    Eaddrnotavail,
    Eadv,
    Eafnosupport,
    Eagain,
    Ealready,
    Eauth,
    Ebackground,
    Ebade,
    Ebadf,
    Ebadfd,
    Ebadmsg,
    Ebadr,
    Ebadrpc,
    Ebadrqc,
    Ebadslt,
    Ebfont,
    Ebusy,
    Ecanceled,
    Echild,
    Echrng,
    Ecomm,
    Econnaborted,
    Econnrefused,
    Econnreset,
    Ed,
    Edeadlk,
    Edeadlock,
    Edestaddrreq,
    Edied,
    Edom,
    Edotdot,
    Edquot,
    Eexist,
    Efault,
    Efbig,
    Eftype,
    Egratuitous,
    Egregious,
    Ehostdown,
    Ehostunreach,
    Eidrm,
    Eieio,
    Eilseq,
    Einprogress,
    Eintr,
    Einval,
    Eio,
    Eisconn,
    Eisdir,
    Eisnam,
    El2hlt,
    El2nsync,
    El3hlt,
    El3rst,
    Elibacc,
    Elibbad,
    Elibexec,
    Elibmax,
    Elibscn,
    Elnrng,
    Eloop,
    Emediumtype,
    Emfile,
    Emlink,
    Emsgsize,
    Emultihop,
    Enametoolong,
    Enavail,
    Eneedauth,
    Enetdown,
    Enetreset,
    Enetunreach,
    Enfile,
    Enoano,
    Enobufs,
    Enocsi,
    Enodata,
    Enodev,
    Enoent,
    Enoexec,
    Enolck,
    Enolink,
    Enomedium,
    Enomem,
    Enomsg,
    Enonet,
    Enopkg,
    Enoprotoopt,
    Enospc,
    Enosr,
    Enostr,
    Enosys,
    Enotblk,
    Enotconn,
    Enotdir,
    Enotempty,
    Enotnam,
    Enotsock,
    Enotsup,
    Enotty,
    Enotuniq,
    Enxio,
    Eopnotsupp,
    Eoverflow,
    Eperm,
    Epfnosupport,
    Epipe,
    Eproclim,
    Eprocunavail,
    Eprogmismatch,
    Eprogunavail,
    Eproto,
    Eprotonosupport,
    Eprototype,
    Erange,
    Eremchg,
    Eremote,
    Eremoteio,
    Erestart,
    Erofs,
    Erpcmismatch,
    Eshutdown,
    Esocktnosupport,
    Espipe,
    Esrch,
    Esrmnt,
    Estale,
    Estrpipe,
    Etime,
    Etimedout,
    Etoomanyrefs,
    Etxtbsy,
    Euclean,
    Eunatch,
    Eusers,
    Ewouldblock,
    Exdev,
    Exfull,
}

impl From<GpgErrorCode> for u16 {
    fn from(val: GpgErrorCode) -> Self {
        match val {
            GpgErrorCode::NoError => 0,
            GpgErrorCode::General => 1,
            GpgErrorCode::UnknownPacket => 2,
            GpgErrorCode::UnknownVersion => 3,
            GpgErrorCode::PubkeyAlgo => 4,
            GpgErrorCode::DigestAlgo => 5,
            GpgErrorCode::BadPubkey => 6,
            GpgErrorCode::BadSeckey => 7,
            GpgErrorCode::BadSignature => 8,
            GpgErrorCode::NoPubkey => 9,
            GpgErrorCode::Checksum => 10,
            GpgErrorCode::BadPassphrase => 11,
            GpgErrorCode::CipherAlgo => 12,
            GpgErrorCode::KeyringOpen => 13,
            GpgErrorCode::InvPacket => 14,
            GpgErrorCode::InvArmor => 15,
            GpgErrorCode::NoUserId => 16,
            GpgErrorCode::NoSeckey => 17,
            GpgErrorCode::WrongSeckey => 18,
            GpgErrorCode::BadKey => 19,
            GpgErrorCode::ComprAlgo => 20,
            GpgErrorCode::NoPrime => 21,
            GpgErrorCode::NoEncodingMethod => 22,
            GpgErrorCode::NoEncryptionScheme => 23,
            GpgErrorCode::NoSignatureScheme => 24,
            GpgErrorCode::InvAttr => 25,
            GpgErrorCode::NoValue => 26,
            GpgErrorCode::NotFound => 27,
            GpgErrorCode::ValueNotFound => 28,
            GpgErrorCode::Syntax => 29,
            GpgErrorCode::BadMpi => 30,
            GpgErrorCode::InvPassphrase => 31,
            GpgErrorCode::SigClass => 32,
            GpgErrorCode::ResourceLimit => 33,
            GpgErrorCode::InvKeyring => 34,
            GpgErrorCode::Trustdb => 35,
            GpgErrorCode::BadCert => 36,
            GpgErrorCode::InvUserId => 37,
            GpgErrorCode::Unexpected => 38,
            GpgErrorCode::TimeConflict => 39,
            GpgErrorCode::Keyserver => 40,
            GpgErrorCode::WrongPubkeyAlgo => 41,
            GpgErrorCode::TributeToDA => 42,
            GpgErrorCode::WeakKey => 43,
            GpgErrorCode::InvKeylen => 44,
            GpgErrorCode::InvArg => 45,
            GpgErrorCode::BadUri => 46,
            GpgErrorCode::InvUri => 47,
            GpgErrorCode::Network => 48,
            GpgErrorCode::UnknownHost => 49,
            GpgErrorCode::SelftestFailed => 50,
            GpgErrorCode::NotEncrypted => 51,
            GpgErrorCode::NotProcessed => 52,
            GpgErrorCode::UnusablePubkey => 53,
            GpgErrorCode::UnusableSeckey => 54,
            GpgErrorCode::InvValue => 55,
            GpgErrorCode::BadCertChain => 56,
            GpgErrorCode::MissingCert => 57,
            GpgErrorCode::NoData => 58,
            GpgErrorCode::Bug => 59,
            GpgErrorCode::NotSupported => 60,
            GpgErrorCode::InvOp => 61,
            GpgErrorCode::Timeout => 62,
            GpgErrorCode::Internal => 63,
            GpgErrorCode::EofGcrypt => 64,
            GpgErrorCode::InvObj => 65,
            GpgErrorCode::TooShort => 66,
            GpgErrorCode::TooLarge => 67,
            GpgErrorCode::NoObj => 68,
            GpgErrorCode::NotImplemented => 69,
            GpgErrorCode::Conflict => 70,
            GpgErrorCode::InvCipherMode => 71,
            GpgErrorCode::InvFlag => 72,
            GpgErrorCode::InvHandle => 73,
            GpgErrorCode::Truncated => 74,
            GpgErrorCode::IncompleteLine => 75,
            GpgErrorCode::InvResponse => 76,
            GpgErrorCode::NoAgent => 77,
            GpgErrorCode::Agent => 78,
            GpgErrorCode::InvData => 79,
            GpgErrorCode::AssuanServerFault => 80,
            GpgErrorCode::Assuan => 81,
            GpgErrorCode::InvSessionKey => 82,
            GpgErrorCode::InvSexp => 83,
            GpgErrorCode::UnsupportedAlgorithm => 84,
            GpgErrorCode::NoPinEntry => 85,
            GpgErrorCode::PinEntry => 86,
            GpgErrorCode::BadPin => 87,
            GpgErrorCode::InvName => 88,
            GpgErrorCode::BadData => 89,
            GpgErrorCode::InvParameter => 90,
            GpgErrorCode::WrongCard => 91,
            GpgErrorCode::NoDirmngr => 92,
            GpgErrorCode::Dirmngr => 93,
            GpgErrorCode::CertRevoked => 94,
            GpgErrorCode::NoCrlKnown => 95,
            GpgErrorCode::CrlTooOld => 96,
            GpgErrorCode::LineTooLong => 97,
            GpgErrorCode::NotTrusted => 98,
            GpgErrorCode::Canceled => 99,
            GpgErrorCode::BadCaCert => 100,
            GpgErrorCode::CertExpired => 101,
            GpgErrorCode::CertTooYoung => 102,
            GpgErrorCode::UnsupportedCert => 103,
            GpgErrorCode::UnknownSexp => 104,
            GpgErrorCode::UnsupportedProtection => 105,
            GpgErrorCode::CorruptedProtection => 106,
            GpgErrorCode::AmbiguousName => 107,
            GpgErrorCode::Card => 108,
            GpgErrorCode::CardReset => 109,
            GpgErrorCode::CardRemoved => 110,
            GpgErrorCode::InvCard => 111,
            GpgErrorCode::CardNotPresent => 112,
            GpgErrorCode::NoPkcs15App => 113,
            GpgErrorCode::NotConfirmed => 114,
            GpgErrorCode::Configuration => 115,
            GpgErrorCode::NoPolicyMatch => 116,
            GpgErrorCode::InvIndex => 117,
            GpgErrorCode::InvId => 118,
            GpgErrorCode::NoScdaemon => 119,
            GpgErrorCode::Scdaemon => 120,
            GpgErrorCode::UnsupportedProtocol => 121,
            GpgErrorCode::BadPinMethod => 122,
            GpgErrorCode::CardNotInitialized => 123,
            GpgErrorCode::UnsupportedOperation => 124,
            GpgErrorCode::WrongKeyUsage => 125,
            GpgErrorCode::NothingFound => 126,
            GpgErrorCode::WrongBlobType => 127,
            GpgErrorCode::MissingValue => 128,
            GpgErrorCode::Hardware => 129,
            GpgErrorCode::PinBlocked => 130,
            GpgErrorCode::UseConditions => 131,
            GpgErrorCode::PinNotSynced => 132,
            GpgErrorCode::InvCrl => 133,
            GpgErrorCode::BadBer => 134,
            GpgErrorCode::InvBer => 135,
            GpgErrorCode::ElementNotFound => 136,
            GpgErrorCode::IdentifierNotFound => 137,
            GpgErrorCode::InvTag => 138,
            GpgErrorCode::InvLength => 139,
            GpgErrorCode::InvKeyinfo => 140,
            GpgErrorCode::UnexpectedTag => 141,
            GpgErrorCode::NotDerEncoded => 142,
            GpgErrorCode::NoCmsObj => 143,
            GpgErrorCode::InvCmsObj => 144,
            GpgErrorCode::UnknownCmsObj => 145,
            GpgErrorCode::UnsupportedCmsObj => 146,
            GpgErrorCode::UnsupportedEncoding => 147,
            GpgErrorCode::UnsupportedCmsVersion => 148,
            GpgErrorCode::UnknownAlgorithm => 149,
            GpgErrorCode::InvEngine => 150,
            GpgErrorCode::PubkeyNotTrusted => 151,
            GpgErrorCode::DecryptFailed => 152,
            GpgErrorCode::KeyExpired => 153,
            GpgErrorCode::SigExpired => 154,
            GpgErrorCode::EncodingProblem => 155,
            GpgErrorCode::InvState => 156,
            GpgErrorCode::DupValue => 157,
            GpgErrorCode::MissingAction => 158,
            GpgErrorCode::ModuleNotFound => 159,
            GpgErrorCode::InvOidString => 160,
            GpgErrorCode::InvTime => 161,
            GpgErrorCode::InvCrlObj => 162,
            GpgErrorCode::UnsupportedCrlVersion => 163,
            GpgErrorCode::InvCertObj => 164,
            GpgErrorCode::UnknownName => 165,
            GpgErrorCode::LocaleProblem => 166,
            GpgErrorCode::NotLocked => 167,
            GpgErrorCode::ProtocolViolation => 168,
            GpgErrorCode::InvMac => 169,
            GpgErrorCode::InvRequest => 170,
            GpgErrorCode::UnknownExtn => 171,
            GpgErrorCode::UnknownCritExtn => 172,
            GpgErrorCode::Locked => 173,
            GpgErrorCode::UnknownOption => 174,
            GpgErrorCode::UnknownCommand => 175,
            GpgErrorCode::NotOperational => 176,
            GpgErrorCode::NoPassphrase => 177,
            GpgErrorCode::NoPin => 178,
            GpgErrorCode::NotEnabled => 179,
            GpgErrorCode::NoEngine => 180,
            GpgErrorCode::MissingKey => 181,
            GpgErrorCode::TooMany => 182,
            GpgErrorCode::LimitReached => 183,
            GpgErrorCode::NotInitialized => 184,
            GpgErrorCode::MissingIssuerCert => 185,
            GpgErrorCode::NoKeyserver => 186,
            GpgErrorCode::InvCurve => 187,
            GpgErrorCode::UnknownCurve => 188,
            GpgErrorCode::DupKey => 189,
            GpgErrorCode::Ambiguous => 190,
            GpgErrorCode::NoCryptCtx => 191,
            GpgErrorCode::WrongCryptCtx => 192,
            GpgErrorCode::BadCryptCtx => 193,
            GpgErrorCode::CryptCtxConflict => 194,
            GpgErrorCode::BrokenPubkey => 195,
            GpgErrorCode::BrokenSeckey => 196,
            GpgErrorCode::MacAlgo => 197,
            GpgErrorCode::FullyCanceled => 198,
            GpgErrorCode::Unfinished => 199,

            GpgErrorCode::BufferTooShort => 200,
            GpgErrorCode::SexpInvLenSpec => 201,
            GpgErrorCode::SexpStringTooLong => 202,
            GpgErrorCode::SexpUnmatchedParen => 203,
            GpgErrorCode::SexpNotCanonical => 204,
            GpgErrorCode::SexpBadCharacter => 205,
            GpgErrorCode::SexpBadQuotation => 206,
            GpgErrorCode::SexpZeroPrefix => 207,
            GpgErrorCode::SexpNestedDh => 208,
            GpgErrorCode::SexpUnmatchedDh => 209,
            GpgErrorCode::SexpUnexpectedPunc => 210,
            GpgErrorCode::SexpBadHexChar => 211,
            GpgErrorCode::SexpOddHexNumbers => 212,
            GpgErrorCode::SexpBadOctChar => 213,
            GpgErrorCode::SubkeysExpOrRev => 217,
            GpgErrorCode::DbCorrupted => 218,
            GpgErrorCode::ServerFailed => 219,
            GpgErrorCode::NoName => 220,
            GpgErrorCode::NoKey => 221,
            GpgErrorCode::LegacyKey => 222,
            GpgErrorCode::RequestTooShort => 223,
            GpgErrorCode::RequestTooLong => 224,
            GpgErrorCode::ObjTermState => 225,
            GpgErrorCode::NoCertChain => 226,
            GpgErrorCode::CertTooLarge => 227,
            GpgErrorCode::InvRecord => 228,
            GpgErrorCode::BadMac => 229,
            GpgErrorCode::UnexpectedMsg => 230,
            GpgErrorCode::ComprFailed => 231,
            GpgErrorCode::WouldWrap => 232,
            GpgErrorCode::FatalAlert => 233,
            GpgErrorCode::NoCipher => 234,
            GpgErrorCode::MissingClientCert => 235,
            GpgErrorCode::CloseNotify => 236,
            GpgErrorCode::TicketExpired => 237,
            GpgErrorCode::BadTicket => 238,
            GpgErrorCode::UnknownIdentity => 239,
            GpgErrorCode::BadHsCert => 240,
            GpgErrorCode::BadHsCertReq => 241,
            GpgErrorCode::BadHsCertVer => 242,
            GpgErrorCode::BadHsChangeCipher => 243,
            GpgErrorCode::BadHsClientHello => 244,
            GpgErrorCode::BadHsServerHello => 245,
            GpgErrorCode::BadHsServerHelloDone => 246,
            GpgErrorCode::BadHsFinished => 247,
            GpgErrorCode::BadHsServerKex => 248,
            GpgErrorCode::BadHsClientKex => 249,
            GpgErrorCode::BogusString => 250,
            GpgErrorCode::Forbidden => 251,
            GpgErrorCode::KeyDisabled => 252,
            GpgErrorCode::KeyOnCard => 253,
            GpgErrorCode::InvLockObj => 254,
            GpgErrorCode::True => 255,
            GpgErrorCode::False => 256,
            GpgErrorCode::AssGeneral => 257,
            GpgErrorCode::AssAcceptFailed => 258,
            GpgErrorCode::AssConnectFailed => 259,
            GpgErrorCode::AssInvResponse => 260,
            GpgErrorCode::AssInvValue => 261,
            GpgErrorCode::AssIncompleteLine => 262,
            GpgErrorCode::AssLineTooLong => 263,
            GpgErrorCode::AssNestedCommands => 264,
            GpgErrorCode::AssNoDataCb => 265,
            GpgErrorCode::AssNoInquireCb => 266,
            GpgErrorCode::AssNotAServer => 267,
            GpgErrorCode::AssNotAClient => 268,
            GpgErrorCode::AssServerStart => 269,
            GpgErrorCode::AssReadError => 270,
            GpgErrorCode::AssWriteError => 271,
            GpgErrorCode::AssTooMuchData => 273,
            GpgErrorCode::AssUnexpectedCmd => 274,
            GpgErrorCode::AssUnknownCmd => 275,
            GpgErrorCode::AssSyntax => 276,
            GpgErrorCode::AssCanceled => 277,
            GpgErrorCode::AssNoInput => 278,
            GpgErrorCode::AssNoOutput => 279,
            GpgErrorCode::AssParameter => 280,
            GpgErrorCode::AssUnknownInquire => 281,

            GpgErrorCode::EngineTooOld => 300,
            GpgErrorCode::WindowTooSmall => 301,
            GpgErrorCode::WindowTooLarge => 302,
            GpgErrorCode::MissingEnvvar => 303,
            GpgErrorCode::UserIdExists => 304,
            GpgErrorCode::NameExists => 305,
            GpgErrorCode::DupName => 306,
            GpgErrorCode::TooYoung => 307,
            GpgErrorCode::TooOld => 308,
            GpgErrorCode::UnknownFlag => 309,
            GpgErrorCode::InvOrder => 310,
            GpgErrorCode::AlreadyFetched => 311,
            GpgErrorCode::TryLater => 312,
            GpgErrorCode::WrongName => 313,
            GpgErrorCode::NoAuth => 314,
            GpgErrorCode::BadAuth => 315,
            GpgErrorCode::NoKeyboxd => 316,
            GpgErrorCode::Keyboxd => 317,
            GpgErrorCode::NoService => 318,
            GpgErrorCode::Service => 319,
            GpgErrorCode::BadPuk => 320,
            GpgErrorCode::NoResetCode => 321,
            GpgErrorCode::BadResetCode => 322,

            GpgErrorCode::SystemBug => 666,
            GpgErrorCode::DnsUnknown => 711,
            GpgErrorCode::DnsSection => 712,
            GpgErrorCode::DnsAddress => 713,
            GpgErrorCode::DnsNoQuery => 714,
            GpgErrorCode::DnsNoAnswer => 715,
            GpgErrorCode::DnsClosed => 716,
            GpgErrorCode::DnsVerify => 717,
            GpgErrorCode::DnsTimeout => 718,
            GpgErrorCode::LdapGeneral => 721,
            GpgErrorCode::LdapAttrGeneral => 722,
            GpgErrorCode::LdapNameGeneral => 723,
            GpgErrorCode::LdapSecurityGeneral => 724,
            GpgErrorCode::LdapServiceGeneral => 725,
            GpgErrorCode::LdapUpdateGeneral => 726,
            GpgErrorCode::LdapEGeneral => 727,
            GpgErrorCode::LdapXGeneral => 728,
            GpgErrorCode::LdapOtherGeneral => 729,
            GpgErrorCode::LdapXConnecting => 750,
            GpgErrorCode::LdapReferralLimit => 751,
            GpgErrorCode::LdapClientLoop => 752,
            GpgErrorCode::LdapNoResults => 754,
            GpgErrorCode::LdapControlNotFound => 755,
            GpgErrorCode::LdapNotSupported => 756,
            GpgErrorCode::LdapConnect => 757,
            GpgErrorCode::LdapNoMemory => 758,
            GpgErrorCode::LdapParam => 759,
            GpgErrorCode::LdapUserCancelled => 760,
            GpgErrorCode::LdapFilter => 761,
            GpgErrorCode::LdapAuthUnknown => 762,
            GpgErrorCode::LdapTimeout => 763,
            GpgErrorCode::LdapDecoding => 764,
            GpgErrorCode::LdapEncoding => 765,
            GpgErrorCode::LdapLocal => 766,
            GpgErrorCode::LdapServerDown => 767,
            GpgErrorCode::LdapSuccess => 768,
            GpgErrorCode::LdapOperations => 769,
            GpgErrorCode::LdapProtocol => 770,
            GpgErrorCode::LdapTimelimit => 771,
            GpgErrorCode::LdapSizelimit => 772,
            GpgErrorCode::LdapCompareFalse => 773,
            GpgErrorCode::LdapCompareTrue => 774,
            GpgErrorCode::LdapUnsupportedAuth => 775,
            GpgErrorCode::LdapStrongAuthRqrd => 776,
            GpgErrorCode::LdapPartialResults => 777,
            GpgErrorCode::LdapReferral => 778,
            GpgErrorCode::LdapAdminlimit => 779,
            GpgErrorCode::LdapUnavailCritExtn => 780,
            GpgErrorCode::LdapConfidentRqrd => 781,
            GpgErrorCode::LdapSaslBindInprog => 782,
            GpgErrorCode::LdapNoSuchAttribute => 784,
            GpgErrorCode::LdapUndefinedType => 785,
            GpgErrorCode::LdapBadMatching => 786,
            GpgErrorCode::LdapConstViolation => 787,
            GpgErrorCode::LdapTypeValueExists => 788,
            GpgErrorCode::LdapInvSyntax => 789,
            GpgErrorCode::LdapNoSuchObj => 800,
            GpgErrorCode::LdapAliasProblem => 801,
            GpgErrorCode::LdapInvDnSyntax => 802,
            GpgErrorCode::LdapIsLeaf => 803,
            GpgErrorCode::LdapAliasDeref => 804,
            GpgErrorCode::LdapXProxyAuthFail => 815,
            GpgErrorCode::LdapBadAuth => 816,
            GpgErrorCode::LdapInvCredentials => 817,
            GpgErrorCode::LdapInsufficientAcc => 818,
            GpgErrorCode::LdapBusy => 819,
            GpgErrorCode::LdapUnavailable => 820,
            GpgErrorCode::LdapUnwillToPerform => 821,
            GpgErrorCode::LdapLoopDetect => 822,
            GpgErrorCode::LdapNamingViolation => 832,
            GpgErrorCode::LdapObjClsViolation => 833,
            GpgErrorCode::LdapNotAllowNonleaf => 834,
            GpgErrorCode::LdapNotAllowOnRdn => 835,
            GpgErrorCode::LdapAlreadyExists => 836,
            GpgErrorCode::LdapNoObjClassMods => 837,
            GpgErrorCode::LdapResultsTooLarge => 838,
            GpgErrorCode::LdapAffectsMultDsas => 839,
            GpgErrorCode::LdapVlv => 844,
            GpgErrorCode::LdapOther => 848,
            GpgErrorCode::LdapCupResourceLimit => 881,
            GpgErrorCode::LdapCupSecViolation => 882,
            GpgErrorCode::LdapCupInvData => 883,
            GpgErrorCode::LdapCupUnsupScheme => 884,
            GpgErrorCode::LdapCupReload => 885,
            GpgErrorCode::LdapCancelled => 886,
            GpgErrorCode::LdapNoSuchOperation => 887,
            GpgErrorCode::LdapTooLate => 888,
            GpgErrorCode::LdapCannotCancel => 889,
            GpgErrorCode::LdapAssertionFailed => 890,
            GpgErrorCode::LdapProxAuthDenied => 891,
            GpgErrorCode::User1 => 1024,
            GpgErrorCode::User2 => 1025,
            GpgErrorCode::User3 => 1026,
            GpgErrorCode::User4 => 1027,
            GpgErrorCode::User5 => 1028,
            GpgErrorCode::User6 => 1029,
            GpgErrorCode::User7 => 1030,
            GpgErrorCode::User8 => 1031,
            GpgErrorCode::User9 => 1032,
            GpgErrorCode::User10 => 1033,
            GpgErrorCode::User11 => 1034,
            GpgErrorCode::User12 => 1035,
            GpgErrorCode::User13 => 1036,
            GpgErrorCode::User14 => 1037,
            GpgErrorCode::User15 => 1038,
            GpgErrorCode::User16 => 1039,
            GpgErrorCode::SqlOk => 1500,
            GpgErrorCode::SqlError => 1501,
            GpgErrorCode::SqlInternal => 1502,
            GpgErrorCode::SqlPerm => 1503,
            GpgErrorCode::SqlAbort => 1504,
            GpgErrorCode::SqlBusy => 1505,
            GpgErrorCode::SqlLocked => 1506,
            GpgErrorCode::SqlNomem => 1507,
            GpgErrorCode::SqlReadonly => 1508,
            GpgErrorCode::SqlInterrupt => 1509,
            GpgErrorCode::SqlIoerr => 1510,
            GpgErrorCode::SqlCorrupt => 1511,
            GpgErrorCode::SqlNotfound => 1512,
            GpgErrorCode::SqlFull => 1513,
            GpgErrorCode::SqlCantopen => 1514,
            GpgErrorCode::SqlProtocol => 1515,
            GpgErrorCode::SqlEmpty => 1516,
            GpgErrorCode::SqlSchema => 1517,
            GpgErrorCode::SqlToobig => 1518,
            GpgErrorCode::SqlConstraint => 1519,
            GpgErrorCode::SqlMismatch => 1520,
            GpgErrorCode::SqlMisuse => 1521,
            GpgErrorCode::SqlNolfs => 1522,
            GpgErrorCode::SqlAuth => 1523,
            GpgErrorCode::SqlFormat => 1524,
            GpgErrorCode::SqlRange => 1525,
            GpgErrorCode::SqlNotadb => 1526,
            GpgErrorCode::SqlNotice => 1527,
            GpgErrorCode::SqlWarning => 1528,
            GpgErrorCode::SqlRow => 1600,
            GpgErrorCode::SqlDone => 1601,
            GpgErrorCode::MissingErrno => 16381,
            GpgErrorCode::UnknownErrno => 16382,
            GpgErrorCode::Eof => 16383,

            GpgErrorCode::E2big => 1 << 15,
            GpgErrorCode::Eacces => 32768 + 1,
            GpgErrorCode::Eaddrinuse => 32768 + 2,
            GpgErrorCode::Eaddrnotavail => 32768 + 3,
            GpgErrorCode::Eadv => 32768 + 4,
            GpgErrorCode::Eafnosupport => 32768 + 5,
            GpgErrorCode::Eagain => 32768 + 6,
            GpgErrorCode::Ealready => 32768 + 7,
            GpgErrorCode::Eauth => 32768 + 8,
            GpgErrorCode::Ebackground => 32768 + 9,
            GpgErrorCode::Ebade => 32768 + 10,
            GpgErrorCode::Ebadf => 32768 + 11,
            GpgErrorCode::Ebadfd => 32768 + 12,
            GpgErrorCode::Ebadmsg => 32768 + 13,
            GpgErrorCode::Ebadr => 32768 + 14,
            GpgErrorCode::Ebadrpc => 32768 + 15,
            GpgErrorCode::Ebadrqc => 32768 + 16,
            GpgErrorCode::Ebadslt => 32768 + 17,
            GpgErrorCode::Ebfont => 32768 + 18,
            GpgErrorCode::Ebusy => 32768 + 19,
            GpgErrorCode::Ecanceled => 32768 + 20,
            GpgErrorCode::Echild => 32768 + 21,
            GpgErrorCode::Echrng => 32768 + 22,
            GpgErrorCode::Ecomm => 32768 + 23,
            GpgErrorCode::Econnaborted => 32768 + 24,
            GpgErrorCode::Econnrefused => 32768 + 25,
            GpgErrorCode::Econnreset => 32768 + 26,
            GpgErrorCode::Ed => 32768 + 27,
            GpgErrorCode::Edeadlk => 32768 + 28,
            GpgErrorCode::Edeadlock => 32768 + 29,
            GpgErrorCode::Edestaddrreq => 32768 + 30,
            GpgErrorCode::Edied => 32768 + 31,
            GpgErrorCode::Edom => 32768 + 32,
            GpgErrorCode::Edotdot => 32768 + 33,
            GpgErrorCode::Edquot => 32768 + 34,
            GpgErrorCode::Eexist => 32768 + 35,
            GpgErrorCode::Efault => 32768 + 36,
            GpgErrorCode::Efbig => 32768 + 37,
            GpgErrorCode::Eftype => 32768 + 38,
            GpgErrorCode::Egratuitous => 32768 + 39,
            GpgErrorCode::Egregious => 32768 + 40,
            GpgErrorCode::Ehostdown => 32768 + 41,
            GpgErrorCode::Ehostunreach => 32768 + 42,
            GpgErrorCode::Eidrm => 32768 + 43,
            GpgErrorCode::Eieio => 32768 + 44,
            GpgErrorCode::Eilseq => 32768 + 45,
            GpgErrorCode::Einprogress => 32768 + 46,
            GpgErrorCode::Eintr => 32768 + 47,
            GpgErrorCode::Einval => 32768 + 48,
            GpgErrorCode::Eio => 32768 + 49,
            GpgErrorCode::Eisconn => 32768 + 50,
            GpgErrorCode::Eisdir => 32768 + 51,
            GpgErrorCode::Eisnam => 32768 + 52,
            GpgErrorCode::El2hlt => 32768 + 53,
            GpgErrorCode::El2nsync => 32768 + 54,
            GpgErrorCode::El3hlt => 32768 + 55,
            GpgErrorCode::El3rst => 32768 + 56,
            GpgErrorCode::Elibacc => 32768 + 57,
            GpgErrorCode::Elibbad => 32768 + 58,
            GpgErrorCode::Elibexec => 32768 + 59,
            GpgErrorCode::Elibmax => 32768 + 60,
            GpgErrorCode::Elibscn => 32768 + 61,
            GpgErrorCode::Elnrng => 32768 + 62,
            GpgErrorCode::Eloop => 32768 + 63,
            GpgErrorCode::Emediumtype => 32768 + 64,
            GpgErrorCode::Emfile => 32768 + 65,
            GpgErrorCode::Emlink => 32768 + 66,
            GpgErrorCode::Emsgsize => 32768 + 67,
            GpgErrorCode::Emultihop => 32768 + 68,
            GpgErrorCode::Enametoolong => 32768 + 69,
            GpgErrorCode::Enavail => 32768 + 70,
            GpgErrorCode::Eneedauth => 32768 + 71,
            GpgErrorCode::Enetdown => 32768 + 72,
            GpgErrorCode::Enetreset => 32768 + 73,
            GpgErrorCode::Enetunreach => 32768 + 74,
            GpgErrorCode::Enfile => 32768 + 75,
            GpgErrorCode::Enoano => 32768 + 76,
            GpgErrorCode::Enobufs => 32768 + 77,
            GpgErrorCode::Enocsi => 32768 + 78,
            GpgErrorCode::Enodata => 32768 + 79,
            GpgErrorCode::Enodev => 32768 + 80,
            GpgErrorCode::Enoent => 32768 + 81,
            GpgErrorCode::Enoexec => 32768 + 82,
            GpgErrorCode::Enolck => 32768 + 83,
            GpgErrorCode::Enolink => 32768 + 84,
            GpgErrorCode::Enomedium => 32768 + 85,
            GpgErrorCode::Enomem => 32768 + 86,
            GpgErrorCode::Enomsg => 32768 + 87,
            GpgErrorCode::Enonet => 32768 + 88,
            GpgErrorCode::Enopkg => 32768 + 89,
            GpgErrorCode::Enoprotoopt => 32768 + 90,
            GpgErrorCode::Enospc => 32768 + 91,
            GpgErrorCode::Enosr => 32768 + 92,
            GpgErrorCode::Enostr => 32768 + 93,
            GpgErrorCode::Enosys => 32768 + 94,
            GpgErrorCode::Enotblk => 32768 + 95,
            GpgErrorCode::Enotconn => 32768 + 96,
            GpgErrorCode::Enotdir => 32768 + 97,
            GpgErrorCode::Enotempty => 32768 + 98,
            GpgErrorCode::Enotnam => 32768 + 99,
            GpgErrorCode::Enotsock => 32768 + 100,
            GpgErrorCode::Enotsup => 32768 + 101,
            GpgErrorCode::Enotty => 32768 + 102,
            GpgErrorCode::Enotuniq => 32768 + 103,
            GpgErrorCode::Enxio => 32768 + 104,
            GpgErrorCode::Eopnotsupp => 32768 + 105,
            GpgErrorCode::Eoverflow => 32768 + 106,
            GpgErrorCode::Eperm => 32768 + 107,
            GpgErrorCode::Epfnosupport => 32768 + 108,
            GpgErrorCode::Epipe => 32768 + 109,
            GpgErrorCode::Eproclim => 32768 + 110,
            GpgErrorCode::Eprocunavail => 32768 + 111,
            GpgErrorCode::Eprogmismatch => 32768 + 112,
            GpgErrorCode::Eprogunavail => 32768 + 113,
            GpgErrorCode::Eproto => 32768 + 114,
            GpgErrorCode::Eprotonosupport => 32768 + 115,
            GpgErrorCode::Eprototype => 32768 + 116,
            GpgErrorCode::Erange => 32768 + 117,
            GpgErrorCode::Eremchg => 32768 + 118,
            GpgErrorCode::Eremote => 32768 + 119,
            GpgErrorCode::Eremoteio => 32768 + 120,
            GpgErrorCode::Erestart => 32768 + 121,
            GpgErrorCode::Erofs => 32768 + 122,
            GpgErrorCode::Erpcmismatch => 32768 + 123,
            GpgErrorCode::Eshutdown => 32768 + 124,
            GpgErrorCode::Esocktnosupport => 32768 + 125,
            GpgErrorCode::Espipe => 32768 + 126,
            GpgErrorCode::Esrch => 32768 + 127,
            GpgErrorCode::Esrmnt => 32768 + 128,
            GpgErrorCode::Estale => 32768 + 129,
            GpgErrorCode::Estrpipe => 32768 + 130,
            GpgErrorCode::Etime => 32768 + 131,
            GpgErrorCode::Etimedout => 32768 + 132,
            GpgErrorCode::Etoomanyrefs => 32768 + 133,
            GpgErrorCode::Etxtbsy => 32768 + 134,
            GpgErrorCode::Euclean => 32768 + 135,
            GpgErrorCode::Eunatch => 32768 + 136,
            GpgErrorCode::Eusers => 32768 + 137,
            GpgErrorCode::Ewouldblock => 32768 + 138,
            GpgErrorCode::Exdev => 32768 + 139,
            GpgErrorCode::Exfull => 32768 + 140,
        }
    }
}

impl<'a> TryFrom<&'a str> for GpgErrorCode {
    type Error = GpgErrorCodeParseError<&'a str>;

    fn try_from(value: &'a str) -> Result<Self, Self::Error> {
        match value {
            "0" => Ok(Self::NoError),
            "1" => Ok(Self::General),
            "2" => Ok(Self::UnknownPacket),
            "3" => Ok(Self::UnknownVersion),
            "4" => Ok(Self::PubkeyAlgo),
            "5" => Ok(Self::DigestAlgo),
            "6" => Ok(Self::BadPubkey),
            "7" => Ok(Self::BadSeckey),
            "8" => Ok(Self::BadSignature),
            "9" => Ok(Self::NoPubkey),
            "10" => Ok(Self::Checksum),
            "11" => Ok(Self::BadPassphrase),
            "12" => Ok(Self::CipherAlgo),
            "13" => Ok(Self::KeyringOpen),
            "14" => Ok(Self::InvPacket),
            "15" => Ok(Self::InvArmor),
            "16" => Ok(Self::NoUserId),
            "17" => Ok(Self::NoSeckey),
            "18" => Ok(Self::WrongSeckey),
            "19" => Ok(Self::BadKey),
            "20" => Ok(Self::ComprAlgo),
            "21" => Ok(Self::NoPrime),
            "22" => Ok(Self::NoEncodingMethod),
            "23" => Ok(Self::NoEncryptionScheme),
            "24" => Ok(Self::NoSignatureScheme),
            "25" => Ok(Self::InvAttr),
            "26" => Ok(Self::NoValue),
            "27" => Ok(Self::NotFound),
            "28" => Ok(Self::ValueNotFound),
            "29" => Ok(Self::Syntax),
            "30" => Ok(Self::BadMpi),
            "31" => Ok(Self::InvPassphrase),
            "32" => Ok(Self::SigClass),
            "33" => Ok(Self::ResourceLimit),
            "34" => Ok(Self::InvKeyring),
            "35" => Ok(Self::Trustdb),
            "36" => Ok(Self::BadCert),
            "37" => Ok(Self::InvUserId),
            "38" => Ok(Self::Unexpected),
            "39" => Ok(Self::TimeConflict),
            "40" => Ok(Self::Keyserver),
            "41" => Ok(Self::WrongPubkeyAlgo),
            "42" => Ok(Self::TributeToDA),
            "43" => Ok(Self::WeakKey),
            "44" => Ok(Self::InvKeylen),
            "45" => Ok(Self::InvArg),
            "46" => Ok(Self::BadUri),
            "47" => Ok(Self::InvUri),
            "48" => Ok(Self::Network),
            "49" => Ok(Self::UnknownHost),
            "50" => Ok(Self::SelftestFailed),
            "51" => Ok(Self::NotEncrypted),
            "52" => Ok(Self::NotProcessed),
            "53" => Ok(Self::UnusablePubkey),
            "54" => Ok(Self::UnusableSeckey),
            "55" => Ok(Self::InvValue),
            "56" => Ok(Self::BadCertChain),
            "57" => Ok(Self::MissingCert),
            "58" => Ok(Self::NoData),
            "59" => Ok(Self::Bug),
            "60" => Ok(Self::NotSupported),
            "61" => Ok(Self::InvOp),
            "62" => Ok(Self::Timeout),
            "63" => Ok(Self::Internal),
            "64" => Ok(Self::EofGcrypt),
            "65" => Ok(Self::InvObj),
            "66" => Ok(Self::TooShort),
            "67" => Ok(Self::TooLarge),
            "68" => Ok(Self::NoObj),
            "69" => Ok(Self::NotImplemented),
            "70" => Ok(Self::Conflict),
            "71" => Ok(Self::InvCipherMode),
            "72" => Ok(Self::InvFlag),
            "73" => Ok(Self::InvHandle),
            "74" => Ok(Self::Truncated),
            "75" => Ok(Self::IncompleteLine),
            "76" => Ok(Self::InvResponse),
            "77" => Ok(Self::NoAgent),
            "78" => Ok(Self::Agent),
            "79" => Ok(Self::InvData),
            "80" => Ok(Self::AssuanServerFault),
            "81" => Ok(Self::Assuan),
            "82" => Ok(Self::InvSessionKey),
            "83" => Ok(Self::InvSexp),
            "84" => Ok(Self::UnsupportedAlgorithm),
            "85" => Ok(Self::NoPinEntry),
            "86" => Ok(Self::PinEntry),
            "87" => Ok(Self::BadPin),
            "88" => Ok(Self::InvName),
            "89" => Ok(Self::BadData),
            "90" => Ok(Self::InvParameter),
            "91" => Ok(Self::WrongCard),
            "92" => Ok(Self::NoDirmngr),
            "93" => Ok(Self::Dirmngr),
            "94" => Ok(Self::CertRevoked),
            "95" => Ok(Self::NoCrlKnown),
            "96" => Ok(Self::CrlTooOld),
            "97" => Ok(Self::LineTooLong),
            "98" => Ok(Self::NotTrusted),
            "99" => Ok(Self::Canceled),
            "100" => Ok(Self::BadCaCert),
            "101" => Ok(Self::CertExpired),
            "102" => Ok(Self::CertTooYoung),
            "103" => Ok(Self::UnsupportedCert),
            "104" => Ok(Self::UnknownSexp),
            "105" => Ok(Self::UnsupportedProtection),
            "106" => Ok(Self::CorruptedProtection),
            "107" => Ok(Self::AmbiguousName),
            "108" => Ok(Self::Card),
            "109" => Ok(Self::CardReset),
            "110" => Ok(Self::CardRemoved),
            "111" => Ok(Self::InvCard),
            "112" => Ok(Self::CardNotPresent),
            "113" => Ok(Self::NoPkcs15App),
            "114" => Ok(Self::NotConfirmed),
            "115" => Ok(Self::Configuration),
            "116" => Ok(Self::NoPolicyMatch),
            "117" => Ok(Self::InvIndex),
            "118" => Ok(Self::InvId),
            "119" => Ok(Self::NoScdaemon),
            "120" => Ok(Self::Scdaemon),
            "121" => Ok(Self::UnsupportedProtocol),
            "122" => Ok(Self::BadPinMethod),
            "123" => Ok(Self::CardNotInitialized),
            "124" => Ok(Self::UnsupportedOperation),
            "125" => Ok(Self::WrongKeyUsage),
            "126" => Ok(Self::NothingFound),
            "127" => Ok(Self::WrongBlobType),
            "128" => Ok(Self::MissingValue),
            "129" => Ok(Self::Hardware),
            "130" => Ok(Self::PinBlocked),
            "131" => Ok(Self::UseConditions),
            "132" => Ok(Self::PinNotSynced),
            "133" => Ok(Self::InvCrl),
            "134" => Ok(Self::BadBer),
            "135" => Ok(Self::InvBer),
            "136" => Ok(Self::ElementNotFound),
            "137" => Ok(Self::IdentifierNotFound),
            "138" => Ok(Self::InvTag),
            "139" => Ok(Self::InvLength),
            "140" => Ok(Self::InvKeyinfo),
            "141" => Ok(Self::UnexpectedTag),
            "142" => Ok(Self::NotDerEncoded),
            "143" => Ok(Self::NoCmsObj),
            "144" => Ok(Self::InvCmsObj),
            "145" => Ok(Self::UnknownCmsObj),
            "146" => Ok(Self::UnsupportedCmsObj),
            "147" => Ok(Self::UnsupportedEncoding),
            "148" => Ok(Self::UnsupportedCmsVersion),
            "149" => Ok(Self::UnknownAlgorithm),
            "150" => Ok(Self::InvEngine),
            "151" => Ok(Self::PubkeyNotTrusted),
            "152" => Ok(Self::DecryptFailed),
            "153" => Ok(Self::KeyExpired),
            "154" => Ok(Self::SigExpired),
            "155" => Ok(Self::EncodingProblem),
            "156" => Ok(Self::InvState),
            "157" => Ok(Self::DupValue),
            "158" => Ok(Self::MissingAction),
            "159" => Ok(Self::ModuleNotFound),
            "160" => Ok(Self::InvOidString),
            "161" => Ok(Self::InvTime),
            "162" => Ok(Self::InvCrlObj),
            "163" => Ok(Self::UnsupportedCrlVersion),
            "164" => Ok(Self::InvCertObj),
            "165" => Ok(Self::UnknownName),
            "166" => Ok(Self::LocaleProblem),
            "167" => Ok(Self::NotLocked),
            "168" => Ok(Self::ProtocolViolation),
            "169" => Ok(Self::InvMac),
            "170" => Ok(Self::InvRequest),
            "171" => Ok(Self::UnknownExtn),
            "172" => Ok(Self::UnknownCritExtn),
            "173" => Ok(Self::Locked),
            "174" => Ok(Self::UnknownOption),
            "175" => Ok(Self::UnknownCommand),
            "176" => Ok(Self::NotOperational),
            "177" => Ok(Self::NoPassphrase),
            "178" => Ok(Self::NoPin),
            "179" => Ok(Self::NotEnabled),
            "180" => Ok(Self::NoEngine),
            "181" => Ok(Self::MissingKey),
            "182" => Ok(Self::TooMany),
            "183" => Ok(Self::LimitReached),
            "184" => Ok(Self::NotInitialized),
            "185" => Ok(Self::MissingIssuerCert),
            "186" => Ok(Self::NoKeyserver),
            "187" => Ok(Self::InvCurve),
            "188" => Ok(Self::UnknownCurve),
            "189" => Ok(Self::DupKey),
            "190" => Ok(Self::Ambiguous),
            "191" => Ok(Self::NoCryptCtx),
            "192" => Ok(Self::WrongCryptCtx),
            "193" => Ok(Self::BadCryptCtx),
            "194" => Ok(Self::CryptCtxConflict),
            "195" => Ok(Self::BrokenPubkey),
            "196" => Ok(Self::BrokenSeckey),
            "197" => Ok(Self::MacAlgo),
            "198" => Ok(Self::FullyCanceled),
            "199" => Ok(Self::Unfinished),

            "200" => Ok(Self::BufferTooShort),
            "201" => Ok(Self::SexpInvLenSpec),
            "202" => Ok(Self::SexpStringTooLong),
            "203" => Ok(Self::SexpUnmatchedParen),
            "204" => Ok(Self::SexpNotCanonical),
            "205" => Ok(Self::SexpBadCharacter),
            "206" => Ok(Self::SexpBadQuotation),
            "207" => Ok(Self::SexpZeroPrefix),
            "208" => Ok(Self::SexpNestedDh),
            "209" => Ok(Self::SexpUnmatchedDh),
            "210" => Ok(Self::SexpUnexpectedPunc),
            "211" => Ok(Self::SexpBadHexChar),
            "212" => Ok(Self::SexpOddHexNumbers),
            "213" => Ok(Self::SexpBadOctChar),
            "217" => Ok(Self::SubkeysExpOrRev),
            "218" => Ok(Self::DbCorrupted),
            "219" => Ok(Self::ServerFailed),
            "220" => Ok(Self::NoName),
            "221" => Ok(Self::NoKey),
            "222" => Ok(Self::LegacyKey),
            "223" => Ok(Self::RequestTooShort),
            "224" => Ok(Self::RequestTooLong),
            "225" => Ok(Self::ObjTermState),
            "226" => Ok(Self::NoCertChain),
            "227" => Ok(Self::CertTooLarge),
            "228" => Ok(Self::InvRecord),
            "229" => Ok(Self::BadMac),
            "230" => Ok(Self::UnexpectedMsg),
            "231" => Ok(Self::ComprFailed),
            "232" => Ok(Self::WouldWrap),
            "233" => Ok(Self::FatalAlert),
            "234" => Ok(Self::NoCipher),
            "235" => Ok(Self::MissingClientCert),
            "236" => Ok(Self::CloseNotify),
            "237" => Ok(Self::TicketExpired),
            "238" => Ok(Self::BadTicket),
            "239" => Ok(Self::UnknownIdentity),
            "240" => Ok(Self::BadHsCert),
            "241" => Ok(Self::BadHsCertReq),
            "242" => Ok(Self::BadHsCertVer),
            "243" => Ok(Self::BadHsChangeCipher),
            "244" => Ok(Self::BadHsClientHello),
            "245" => Ok(Self::BadHsServerHello),
            "246" => Ok(Self::BadHsServerHelloDone),
            "247" => Ok(Self::BadHsFinished),
            "248" => Ok(Self::BadHsServerKex),
            "249" => Ok(Self::BadHsClientKex),
            "250" => Ok(Self::BogusString),
            "251" => Ok(Self::Forbidden),
            "252" => Ok(Self::KeyDisabled),
            "253" => Ok(Self::KeyOnCard),
            "254" => Ok(Self::InvLockObj),
            "255" => Ok(Self::True),
            "256" => Ok(Self::False),
            "257" => Ok(Self::AssGeneral),
            "258" => Ok(Self::AssAcceptFailed),
            "259" => Ok(Self::AssConnectFailed),
            "260" => Ok(Self::AssInvResponse),
            "261" => Ok(Self::AssInvValue),
            "262" => Ok(Self::AssIncompleteLine),
            "263" => Ok(Self::AssLineTooLong),
            "264" => Ok(Self::AssNestedCommands),
            "265" => Ok(Self::AssNoDataCb),
            "266" => Ok(Self::AssNoInquireCb),
            "267" => Ok(Self::AssNotAServer),
            "268" => Ok(Self::AssNotAClient),
            "269" => Ok(Self::AssServerStart),
            "270" => Ok(Self::AssReadError),
            "271" => Ok(Self::AssWriteError),
            "273" => Ok(Self::AssTooMuchData),
            "274" => Ok(Self::AssUnexpectedCmd),
            "275" => Ok(Self::AssUnknownCmd),
            "276" => Ok(Self::AssSyntax),
            "277" => Ok(Self::AssCanceled),
            "278" => Ok(Self::AssNoInput),
            "279" => Ok(Self::AssNoOutput),
            "280" => Ok(Self::AssParameter),
            "281" => Ok(Self::AssUnknownInquire),

            "300" => Ok(Self::EngineTooOld),
            "301" => Ok(Self::WindowTooSmall),
            "302" => Ok(Self::WindowTooLarge),
            "303" => Ok(Self::MissingEnvvar),
            "304" => Ok(Self::UserIdExists),
            "305" => Ok(Self::NameExists),
            "306" => Ok(Self::DupName),
            "307" => Ok(Self::TooYoung),
            "308" => Ok(Self::TooOld),
            "309" => Ok(Self::UnknownFlag),
            "310" => Ok(Self::InvOrder),
            "311" => Ok(Self::AlreadyFetched),
            "312" => Ok(Self::TryLater),
            "313" => Ok(Self::WrongName),
            "314" => Ok(Self::NoAuth),
            "315" => Ok(Self::BadAuth),
            "316" => Ok(Self::NoKeyboxd),
            "317" => Ok(Self::Keyboxd),
            "318" => Ok(Self::NoService),
            "319" => Ok(Self::Service),
            "320" => Ok(Self::BadPuk),
            "321" => Ok(Self::NoResetCode),
            "322" => Ok(Self::BadResetCode),

            "666" => Ok(Self::SystemBug),

            "711" => Ok(Self::DnsUnknown),
            "712" => Ok(Self::DnsSection),
            "713" => Ok(Self::DnsAddress),
            "714" => Ok(Self::DnsNoQuery),
            "715" => Ok(Self::DnsNoAnswer),
            "716" => Ok(Self::DnsClosed),
            "717" => Ok(Self::DnsVerify),
            "718" => Ok(Self::DnsTimeout),
            "721" => Ok(Self::LdapGeneral),
            "722" => Ok(Self::LdapAttrGeneral),
            "723" => Ok(Self::LdapNameGeneral),
            "724" => Ok(Self::LdapSecurityGeneral),
            "725" => Ok(Self::LdapServiceGeneral),
            "726" => Ok(Self::LdapUpdateGeneral),
            "727" => Ok(Self::LdapEGeneral),
            "728" => Ok(Self::LdapXGeneral),
            "729" => Ok(Self::LdapOtherGeneral),
            "750" => Ok(Self::LdapXConnecting),
            "751" => Ok(Self::LdapReferralLimit),
            "752" => Ok(Self::LdapClientLoop),
            "754" => Ok(Self::LdapNoResults),
            "755" => Ok(Self::LdapControlNotFound),
            "756" => Ok(Self::LdapNotSupported),
            "757" => Ok(Self::LdapConnect),
            "758" => Ok(Self::LdapNoMemory),
            "759" => Ok(Self::LdapParam),
            "760" => Ok(Self::LdapUserCancelled),
            "761" => Ok(Self::LdapFilter),
            "762" => Ok(Self::LdapAuthUnknown),
            "763" => Ok(Self::LdapTimeout),
            "764" => Ok(Self::LdapDecoding),
            "765" => Ok(Self::LdapEncoding),
            "766" => Ok(Self::LdapLocal),
            "767" => Ok(Self::LdapServerDown),
            "768" => Ok(Self::LdapSuccess),
            "769" => Ok(Self::LdapOperations),
            "770" => Ok(Self::LdapProtocol),
            "771" => Ok(Self::LdapTimelimit),
            "772" => Ok(Self::LdapSizelimit),
            "773" => Ok(Self::LdapCompareFalse),
            "774" => Ok(Self::LdapCompareTrue),
            "775" => Ok(Self::LdapUnsupportedAuth),
            "776" => Ok(Self::LdapStrongAuthRqrd),
            "777" => Ok(Self::LdapPartialResults),
            "778" => Ok(Self::LdapReferral),
            "779" => Ok(Self::LdapAdminlimit),
            "780" => Ok(Self::LdapUnavailCritExtn),
            "781" => Ok(Self::LdapConfidentRqrd),
            "782" => Ok(Self::LdapSaslBindInprog),
            "784" => Ok(Self::LdapNoSuchAttribute),
            "785" => Ok(Self::LdapUndefinedType),
            "786" => Ok(Self::LdapBadMatching),
            "787" => Ok(Self::LdapConstViolation),
            "788" => Ok(Self::LdapTypeValueExists),
            "789" => Ok(Self::LdapInvSyntax),
            "800" => Ok(Self::LdapNoSuchObj),
            "801" => Ok(Self::LdapAliasProblem),
            "802" => Ok(Self::LdapInvDnSyntax),
            "803" => Ok(Self::LdapIsLeaf),
            "804" => Ok(Self::LdapAliasDeref),
            "815" => Ok(Self::LdapXProxyAuthFail),
            "816" => Ok(Self::LdapBadAuth),
            "817" => Ok(Self::LdapInvCredentials),
            "818" => Ok(Self::LdapInsufficientAcc),
            "819" => Ok(Self::LdapBusy),
            "820" => Ok(Self::LdapUnavailable),
            "821" => Ok(Self::LdapUnwillToPerform),
            "822" => Ok(Self::LdapLoopDetect),
            "832" => Ok(Self::LdapNamingViolation),
            "833" => Ok(Self::LdapObjClsViolation),
            "834" => Ok(Self::LdapNotAllowNonleaf),
            "835" => Ok(Self::LdapNotAllowOnRdn),
            "836" => Ok(Self::LdapAlreadyExists),
            "837" => Ok(Self::LdapNoObjClassMods),
            "838" => Ok(Self::LdapResultsTooLarge),
            "839" => Ok(Self::LdapAffectsMultDsas),
            "844" => Ok(Self::LdapVlv),
            "848" => Ok(Self::LdapOther),
            "881" => Ok(Self::LdapCupResourceLimit),
            "882" => Ok(Self::LdapCupSecViolation),
            "883" => Ok(Self::LdapCupInvData),
            "884" => Ok(Self::LdapCupUnsupScheme),
            "885" => Ok(Self::LdapCupReload),
            "886" => Ok(Self::LdapCancelled),
            "887" => Ok(Self::LdapNoSuchOperation),
            "888" => Ok(Self::LdapTooLate),
            "889" => Ok(Self::LdapCannotCancel),
            "890" => Ok(Self::LdapAssertionFailed),
            "891" => Ok(Self::LdapProxAuthDenied),

            "1024" => Ok(Self::User1),
            "1025" => Ok(Self::User2),
            "1026" => Ok(Self::User3),
            "1027" => Ok(Self::User4),
            "1028" => Ok(Self::User5),
            "1029" => Ok(Self::User6),
            "1030" => Ok(Self::User7),
            "1031" => Ok(Self::User8),
            "1032" => Ok(Self::User9),
            "1033" => Ok(Self::User10),
            "1034" => Ok(Self::User11),
            "1035" => Ok(Self::User12),
            "1036" => Ok(Self::User13),
            "1037" => Ok(Self::User14),
            "1038" => Ok(Self::User15),
            "1039" => Ok(Self::User16),
            "1500" => Ok(Self::SqlOk),
            "1501" => Ok(Self::SqlError),
            "1502" => Ok(Self::SqlInternal),
            "1503" => Ok(Self::SqlPerm),
            "1504" => Ok(Self::SqlAbort),
            "1505" => Ok(Self::SqlBusy),
            "1506" => Ok(Self::SqlLocked),
            "1507" => Ok(Self::SqlNomem),
            "1508" => Ok(Self::SqlReadonly),
            "1509" => Ok(Self::SqlInterrupt),
            "1510" => Ok(Self::SqlIoerr),
            "1511" => Ok(Self::SqlCorrupt),
            "1512" => Ok(Self::SqlNotfound),
            "1513" => Ok(Self::SqlFull),
            "1514" => Ok(Self::SqlCantopen),
            "1515" => Ok(Self::SqlProtocol),
            "1516" => Ok(Self::SqlEmpty),
            "1517" => Ok(Self::SqlSchema),
            "1518" => Ok(Self::SqlToobig),
            "1519" => Ok(Self::SqlConstraint),
            "1520" => Ok(Self::SqlMismatch),
            "1521" => Ok(Self::SqlMisuse),
            "1522" => Ok(Self::SqlNolfs),
            "1523" => Ok(Self::SqlAuth),
            "1524" => Ok(Self::SqlFormat),
            "1525" => Ok(Self::SqlRange),
            "1526" => Ok(Self::SqlNotadb),
            "1527" => Ok(Self::SqlNotice),
            "1528" => Ok(Self::SqlWarning),
            "1600" => Ok(Self::SqlRow),
            "1601" => Ok(Self::SqlDone),
            "16381" => Ok(Self::MissingErrno),
            "16382" => Ok(Self::UnknownErrno),
            "16383" => Ok(Self::Eof),

            "32768" => Ok(Self::E2big),
            "32769" => Ok(Self::Eacces),
            "32770" => Ok(Self::Eaddrinuse),
            "32771" => Ok(Self::Eaddrnotavail),
            "32772" => Ok(Self::Eadv),
            "32773" => Ok(Self::Eafnosupport),
            "32774" => Ok(Self::Eagain),
            "32775" => Ok(Self::Ealready),
            "32776" => Ok(Self::Eauth),
            "32777" => Ok(Self::Ebackground),
            "32778" => Ok(Self::Ebade),
            "32779" => Ok(Self::Ebadf),
            "32780" => Ok(Self::Ebadfd),
            "32781" => Ok(Self::Ebadmsg),
            "32782" => Ok(Self::Ebadr),
            "32783" => Ok(Self::Ebadrpc),
            "32784" => Ok(Self::Ebadrqc),
            "32785" => Ok(Self::Ebadslt),
            "32786" => Ok(Self::Ebfont),
            "32787" => Ok(Self::Ebusy),
            "32788" => Ok(Self::Ecanceled),
            "32789" => Ok(Self::Echild),
            "32790" => Ok(Self::Echrng),
            "32791" => Ok(Self::Ecomm),
            "32792" => Ok(Self::Econnaborted),
            "32793" => Ok(Self::Econnrefused),
            "32794" => Ok(Self::Econnreset),
            "32795" => Ok(Self::Ed),
            "32796" => Ok(Self::Edeadlk),
            "32797" => Ok(Self::Edeadlock),
            "32798" => Ok(Self::Edestaddrreq),
            "32799" => Ok(Self::Edied),
            "32800" => Ok(Self::Edom),
            "32801" => Ok(Self::Edotdot),
            "32802" => Ok(Self::Edquot),
            "32803" => Ok(Self::Eexist),
            "32804" => Ok(Self::Efault),
            "32805" => Ok(Self::Efbig),
            "32806" => Ok(Self::Eftype),
            "32807" => Ok(Self::Egratuitous),
            "32808" => Ok(Self::Egregious),
            "32809" => Ok(Self::Ehostdown),
            "32810" => Ok(Self::Ehostunreach),
            "32811" => Ok(Self::Eidrm),
            "32812" => Ok(Self::Eieio),
            "32813" => Ok(Self::Eilseq),
            "32814" => Ok(Self::Einprogress),
            "32815" => Ok(Self::Eintr),
            "32816" => Ok(Self::Einval),
            "32817" => Ok(Self::Eio),
            "32818" => Ok(Self::Eisconn),
            "32819" => Ok(Self::Eisdir),
            "32820" => Ok(Self::Eisnam),
            "32821" => Ok(Self::El2hlt),
            "32822" => Ok(Self::El2nsync),
            "32823" => Ok(Self::El3hlt),
            "32824" => Ok(Self::El3rst),
            "32825" => Ok(Self::Elibacc),
            "32826" => Ok(Self::Elibbad),
            "32827" => Ok(Self::Elibexec),
            "32828" => Ok(Self::Elibmax),
            "32829" => Ok(Self::Elibscn),
            "32830" => Ok(Self::Elnrng),
            "32831" => Ok(Self::Eloop),
            "32832" => Ok(Self::Emediumtype),
            "32833" => Ok(Self::Emfile),
            "32834" => Ok(Self::Emlink),
            "32835" => Ok(Self::Emsgsize),
            "32836" => Ok(Self::Emultihop),
            "32837" => Ok(Self::Enametoolong),
            "32838" => Ok(Self::Enavail),
            "32839" => Ok(Self::Eneedauth),
            "32840" => Ok(Self::Enetdown),
            "32841" => Ok(Self::Enetreset),
            "32842" => Ok(Self::Enetunreach),
            "32843" => Ok(Self::Enfile),
            "32844" => Ok(Self::Enoano),
            "32845" => Ok(Self::Enobufs),
            "32846" => Ok(Self::Enocsi),
            "32847" => Ok(Self::Enodata),
            "32848" => Ok(Self::Enodev),
            "32849" => Ok(Self::Enoent),
            "32850" => Ok(Self::Enoexec),
            "32851" => Ok(Self::Enolck),
            "32852" => Ok(Self::Enolink),
            "32853" => Ok(Self::Enomedium),
            "32854" => Ok(Self::Enomem),
            "32855" => Ok(Self::Enomsg),
            "32856" => Ok(Self::Enonet),
            "32857" => Ok(Self::Enopkg),
            "32858" => Ok(Self::Enoprotoopt),
            "32859" => Ok(Self::Enospc),
            "32860" => Ok(Self::Enosr),
            "32861" => Ok(Self::Enostr),
            "32862" => Ok(Self::Enosys),
            "32863" => Ok(Self::Enotblk),
            "32864" => Ok(Self::Enotconn),
            "32865" => Ok(Self::Enotdir),
            "32866" => Ok(Self::Enotempty),
            "32867" => Ok(Self::Enotnam),
            "32868" => Ok(Self::Enotsock),
            "32869" => Ok(Self::Enotsup),
            "32870" => Ok(Self::Enotty),
            "32871" => Ok(Self::Enotuniq),
            "32872" => Ok(Self::Enxio),
            "32873" => Ok(Self::Eopnotsupp),
            "32874" => Ok(Self::Eoverflow),
            "32875" => Ok(Self::Eperm),
            "32876" => Ok(Self::Epfnosupport),
            "32877" => Ok(Self::Epipe),
            "32878" => Ok(Self::Eproclim),
            "32879" => Ok(Self::Eprocunavail),
            "32880" => Ok(Self::Eprogmismatch),
            "32881" => Ok(Self::Eprogunavail),
            "32882" => Ok(Self::Eproto),
            "32883" => Ok(Self::Eprotonosupport),
            "32884" => Ok(Self::Eprototype),
            "32885" => Ok(Self::Erange),
            "32886" => Ok(Self::Eremchg),
            "32887" => Ok(Self::Eremote),
            "32888" => Ok(Self::Eremoteio),
            "32889" => Ok(Self::Erestart),
            "32890" => Ok(Self::Erofs),
            "32891" => Ok(Self::Erpcmismatch),
            "32892" => Ok(Self::Eshutdown),
            "32893" => Ok(Self::Esocktnosupport),
            "32894" => Ok(Self::Espipe),
            "32895" => Ok(Self::Esrch),
            "32896" => Ok(Self::Esrmnt),
            "32897" => Ok(Self::Estale),
            "32898" => Ok(Self::Estrpipe),
            "32899" => Ok(Self::Etime),
            "32900" => Ok(Self::Etimedout),
            "32901" => Ok(Self::Etoomanyrefs),
            "32902" => Ok(Self::Etxtbsy),
            "32903" => Ok(Self::Euclean),
            "32904" => Ok(Self::Eunatch),
            "32905" => Ok(Self::Eusers),
            "32906" => Ok(Self::Ewouldblock),
            "32907" => Ok(Self::Exdev),
            "32908" => Ok(Self::Exfull),
            v => Err(GpgErrorCodeParseError::Unknown(v)),
        }
    }
}

impl fmt::Display for GpgErrorCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let u: u16 = (*self).into();
        write!(f, "{}", u)
    }
}

pub enum GpgErrorCodeParseError<T> {
    Unknown(T),
}

impl TryFrom<u16> for GpgErrorCode {
    type Error = GpgErrorCodeParseError<u16>;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match Self::try_from(value.to_string().as_ref()) {
            Ok(v) => Ok(v),
            Err(_) => Err(GpgErrorCodeParseError::Unknown(value)),
        }
    }
}

#[derive(Debug, PartialEq, Display)]
#[display(fmt = "{}", _0)]
pub struct Custom(pub u16);

impl<'a> TryFrom<&'a str> for Custom {
    type Error = ParseIntError;

    fn try_from(value: &'a str) -> Result<Self, Self::Error> {
        match value.parse::<u16>() {
            Ok(v) => Ok(Custom(v)),
            Err(e) => Err(e),
        }
    }
}
